gh-md-toc: process the md file locally
Avoid github API rate limiting by processing the md file ourselves.

Signed-off-by: Doug Hellmann <dhellmann@redhat.com>

diff --git a/hack/gh-md-toc b/hack/gh-md-toc
--- a/hack/gh-md-toc
+++ b/hack/gh-md-toc
@@ -96,6 +96,19 @@ gh_is_url() {
     esac
 }
 
+mk_slug() {
+    local title="$1"
+    # all lower case
+    # strip some punctuation
+    # replace ' (' with just ' '
+    # replace spaces with dashes
+    echo $title \
+        | tr '[:upper:]' '[:lower:]' \
+        | sed -e 's|[/,)]||g' \
+              -e 's/ (/ /g' \
+              -e 's/ /-/g'
+}
+
 #
 # TOC generator
 #
@@ -136,20 +149,29 @@ gh_toc(){
             echo
         fi
     else
-        local rawhtml=$(gh_toc_md2html "$gh_src")
-        if [ "$rawhtml" == "XXNetworkErrorXX" ]; then
-             echo "Parsing local markdown file requires access to github API"
-             echo "Please make sure curl is installed and check your network connectivity"
-             exit 1
-        fi
-        if [ "$rawhtml" == "XXRateLimitXX" ]; then
-             echo "Parsing local markdown file requires access to github API"
-             echo "Error: You exceeded the hourly limit. See: https://developer.github.com/v3/#rate-limiting"
-             TOKEN_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/token.txt"
-             echo "or place GitHub auth token here: ${TOKEN_FILE}"
-             exit 1
-        fi
-        local toc=`echo "$rawhtml" | gh_toc_grab "$gh_src_copy"`
+        # local rawhtml=$(gh_toc_md2html "$gh_src")
+        # if [ "$rawhtml" == "XXNetworkErrorXX" ]; then
+        #      echo "Parsing local markdown file requires access to github API"
+        #      echo "Please make sure curl is installed and check your network connectivity"
+        #      exit 1
+        # fi
+        # if [ "$rawhtml" == "XXRateLimitXX" ]; then
+        #      echo "Parsing local markdown file requires access to github API"
+        #      echo "Error: You exceeded the hourly limit. See: https://developer.github.com/v3/#rate-limiting"
+        #      TOKEN_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/token.txt"
+        #      echo "or place GitHub auth token here: ${TOKEN_FILE}"
+        #      exit 1
+        # fi
+
+        local toc=$(grep '^#' "$gh_src" \
+                        | while read line; do
+                        title=$(echo "$line" | sed -e 's/^#* *//g')
+                        anchor=$(mk_slug "$title")
+                        bullet=$(echo "$line" | sed -e 's/# .*/-/g' -e 's/#/  /g')
+                        echo "${bullet} [${title}](#${anchor})"
+                    done)
+        #local toc=`echo "$rawhtml" | gh_toc_grab "$gh_src_copy"`
+
         echo "$toc"
         if [ "$need_replace" = "yes" ]; then
             if grep -Fxq "<!--ts-->" $gh_src && grep -Fxq "<!--te-->" $gh_src; then
@@ -168,7 +190,8 @@ gh_toc(){
             # clear old TOC
             sed -i${ext} "/${ts}/,/${te}/{//!d;}" "$gh_src"
             # create toc file
-            echo "${toc}" > "${toc_path}"
+            echo "" > "${toc_path}"
+            echo "${toc}" >> "${toc_path}"
             echo -e "\n${toc_footer}\n" >> "$toc_path"
             # insert toc file
             if [[ "`uname`" == "Darwin" ]]; then
